"""Initial: все существующие таблицы

Revision ID: 1661ef4ba508
Revises: 
Create Date: 2026-03-07 16:41:34.048306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1661ef4ba508'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('min_pv', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_risk_rules_id'), 'risk_rules', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('anketa_create', sa.Boolean(), nullable=False),
    sa.Column('anketa_edit', sa.Boolean(), nullable=False),
    sa.Column('anketa_view_all', sa.Boolean(), nullable=False),
    sa.Column('anketa_conclude', sa.Boolean(), nullable=False),
    sa.Column('anketa_delete', sa.Boolean(), nullable=False),
    sa.Column('user_manage', sa.Boolean(), nullable=False),
    sa.Column('analytics_view', sa.Boolean(), nullable=False),
    sa.Column('export_excel', sa.Boolean(), nullable=False),
    sa.Column('rules_manage', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_table('underwriting_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key')
    )
    op.create_index(op.f('ix_underwriting_rules_id'), 'underwriting_rules', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('anketas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('consent_personal_data', sa.Boolean(), nullable=True),
    sa.Column('client_type', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('passport_series', sa.String(length=20), nullable=True),
    sa.Column('passport_issue_date', sa.Date(), nullable=True),
    sa.Column('passport_issued_by', sa.String(length=200), nullable=True),
    sa.Column('pinfl', sa.String(length=14), nullable=True),
    sa.Column('registration_address', sa.Text(), nullable=True),
    sa.Column('registration_landmark', sa.String(length=300), nullable=True),
    sa.Column('actual_address', sa.Text(), nullable=True),
    sa.Column('actual_landmark', sa.String(length=300), nullable=True),
    sa.Column('phone_numbers', sa.Text(), nullable=True),
    sa.Column('relative_phones', sa.Text(), nullable=True),
    sa.Column('partner', sa.String(length=200), nullable=True),
    sa.Column('car_brand', sa.String(length=100), nullable=True),
    sa.Column('car_model', sa.String(length=100), nullable=True),
    sa.Column('car_specs', sa.String(length=200), nullable=True),
    sa.Column('car_year', sa.Integer(), nullable=True),
    sa.Column('body_number', sa.String(length=100), nullable=True),
    sa.Column('engine_number', sa.String(length=100), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('down_payment_percent', sa.Float(), nullable=True),
    sa.Column('down_payment_amount', sa.Float(), nullable=True),
    sa.Column('remaining_amount', sa.Float(), nullable=True),
    sa.Column('lease_term_months', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('monthly_payment', sa.Float(), nullable=True),
    sa.Column('purchase_purpose', sa.String(length=200), nullable=True),
    sa.Column('has_official_employment', sa.String(length=10), nullable=True),
    sa.Column('employer_name', sa.String(length=300), nullable=True),
    sa.Column('salary_period_months', sa.Float(), nullable=True),
    sa.Column('total_salary', sa.Float(), nullable=True),
    sa.Column('main_activity', sa.String(length=300), nullable=True),
    sa.Column('main_activity_period', sa.Float(), nullable=True),
    sa.Column('main_activity_income', sa.Float(), nullable=True),
    sa.Column('additional_income_source', sa.String(length=300), nullable=True),
    sa.Column('additional_income_period', sa.Float(), nullable=True),
    sa.Column('additional_income_total', sa.Float(), nullable=True),
    sa.Column('other_income_source', sa.String(length=300), nullable=True),
    sa.Column('other_income_period', sa.Float(), nullable=True),
    sa.Column('other_income_total', sa.Float(), nullable=True),
    sa.Column('total_monthly_income', sa.Float(), nullable=True),
    sa.Column('property_type', sa.String(length=200), nullable=True),
    sa.Column('property_details', sa.Text(), nullable=True),
    sa.Column('has_current_obligations', sa.String(length=10), nullable=True),
    sa.Column('total_obligations_amount', sa.Float(), nullable=True),
    sa.Column('obligations_count', sa.Integer(), nullable=True),
    sa.Column('monthly_obligations_payment', sa.Float(), nullable=True),
    sa.Column('dti', sa.Float(), nullable=True),
    sa.Column('closed_obligations_count', sa.Integer(), nullable=True),
    sa.Column('max_overdue_principal_days', sa.Integer(), nullable=True),
    sa.Column('max_overdue_principal_amount', sa.Float(), nullable=True),
    sa.Column('max_continuous_overdue_percent_days', sa.Integer(), nullable=True),
    sa.Column('max_overdue_percent_amount', sa.Float(), nullable=True),
    sa.Column('overdue_category', sa.String(length=20), nullable=True),
    sa.Column('last_overdue_date', sa.Date(), nullable=True),
    sa.Column('overdue_check_result', sa.String(length=100), nullable=True),
    sa.Column('overdue_reason', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('company_inn', sa.String(length=14), nullable=True),
    sa.Column('company_oked', sa.String(length=200), nullable=True),
    sa.Column('company_legal_address', sa.Text(), nullable=True),
    sa.Column('company_actual_address', sa.Text(), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('director_full_name', sa.String(length=300), nullable=True),
    sa.Column('director_phone', sa.String(length=50), nullable=True),
    sa.Column('director_family_phone', sa.String(length=50), nullable=True),
    sa.Column('director_family_relation', sa.String(length=50), nullable=True),
    sa.Column('contact_person_name', sa.String(length=300), nullable=True),
    sa.Column('contact_person_role', sa.String(length=100), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=50), nullable=True),
    sa.Column('company_revenue_period', sa.Float(), nullable=True),
    sa.Column('company_revenue_total', sa.Float(), nullable=True),
    sa.Column('company_net_profit', sa.Float(), nullable=True),
    sa.Column('director_income_period', sa.Float(), nullable=True),
    sa.Column('director_income_total', sa.Float(), nullable=True),
    sa.Column('company_has_obligations', sa.String(length=10), nullable=True),
    sa.Column('company_obligations_amount', sa.Float(), nullable=True),
    sa.Column('company_obligations_count', sa.Integer(), nullable=True),
    sa.Column('company_monthly_payment', sa.Float(), nullable=True),
    sa.Column('company_overdue_category', sa.String(length=20), nullable=True),
    sa.Column('company_last_overdue_date', sa.Date(), nullable=True),
    sa.Column('company_overdue_reason', sa.Text(), nullable=True),
    sa.Column('director_has_obligations', sa.String(length=10), nullable=True),
    sa.Column('director_obligations_amount', sa.Float(), nullable=True),
    sa.Column('director_obligations_count', sa.Integer(), nullable=True),
    sa.Column('director_monthly_payment', sa.Float(), nullable=True),
    sa.Column('director_overdue_category', sa.String(length=20), nullable=True),
    sa.Column('director_last_overdue_date', sa.Date(), nullable=True),
    sa.Column('director_overdue_reason', sa.Text(), nullable=True),
    sa.Column('guarantor_full_name', sa.String(length=300), nullable=True),
    sa.Column('guarantor_pinfl', sa.String(length=14), nullable=True),
    sa.Column('guarantor_passport', sa.String(length=20), nullable=True),
    sa.Column('guarantor_phone', sa.String(length=50), nullable=True),
    sa.Column('guarantor_monthly_income', sa.Float(), nullable=True),
    sa.Column('guarantor_overdue_category', sa.String(length=20), nullable=True),
    sa.Column('guarantor_last_overdue_date', sa.Date(), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('conclusion_comment', sa.Text(), nullable=True),
    sa.Column('concluded_by', sa.Integer(), nullable=True),
    sa.Column('concluded_at', sa.DateTime(), nullable=True),
    sa.Column('pinfl_hash', sa.String(length=64), nullable=True),
    sa.Column('auto_decision', sa.String(length=30), nullable=True),
    sa.Column('auto_decision_reasons', sa.Text(), nullable=True),
    sa.Column('recommended_pv', sa.Float(), nullable=True),
    sa.Column('risk_grade', sa.String(length=50), nullable=True),
    sa.Column('no_scoring_response', sa.Boolean(), nullable=True),
    sa.Column('final_pv', sa.Float(), nullable=True),
    sa.Column('conclusion_version', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['concluded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anketas_id'), 'anketas', ['id'], unique=False)
    op.create_index(op.f('ix_anketas_share_token'), 'anketas', ['share_token'], unique=True)
    op.create_table('anketa_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anketa_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['anketa_id'], ['anketas.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anketa_history_id'), 'anketa_history', ['id'], unique=False)
    op.create_table('anketa_view_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anketa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['anketa_id'], ['anketas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anketa_view_log_id'), 'anketa_view_log', ['id'], unique=False)
    op.create_table('edit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anketa_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anketa_id'], ['anketas.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edit_requests_id'), 'edit_requests', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('anketa_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['anketa_id'], ['anketas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_edit_requests_id'), table_name='edit_requests')
    op.drop_table('edit_requests')
    op.drop_index(op.f('ix_anketa_view_log_id'), table_name='anketa_view_log')
    op.drop_table('anketa_view_log')
    op.drop_index(op.f('ix_anketa_history_id'), table_name='anketa_history')
    op.drop_table('anketa_history')
    op.drop_index(op.f('ix_anketas_share_token'), table_name='anketas')
    op.drop_index(op.f('ix_anketas_id'), table_name='anketas')
    op.drop_table('anketas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_underwriting_rules_id'), table_name='underwriting_rules')
    op.drop_table('underwriting_rules')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_risk_rules_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    # ### end Alembic commands ###
